### ISSUE TITLE
Sort emojis according to unicode emoji list

### ISSUE THREAD

**Issue by atabekm** [kosi-libs/Emoji.kt#3]
Hi, thanks for the library, great work.

I am about to integrate this library to my android keyboard project, but I found out that emojis are sorted randomly (?) within their groups, subgroups, and even within `Emoji.all()` method. I want to list the emojis with the same sequence we have in the emoji list (as all other keyboards with emoji's do), but with current implementation, I need to sort them manually. So, I was just wondering whether it would be possible to have sorting as we have in [Unicode Full Emoji List](https://unicode.org/emoji/charts/full-emoji-list.html)? 

I am happy to do the work, and create PR, if needed. Thanks.

**Comment by SalomonBrys** [comment]
I'll work on this, but I won't be abloe to in the two next weeks.

**Comment by atabekm** [comment]
Thanks @SalomonBrys

**Comment by SalomonBrys** [comment]
Fixed in 2.0.0
